name: KRCL Show Archiver

on:
  workflow_dispatch:

jobs:
  archive-shows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl jq zstd tar

      - name: Make working directory
        run: mkdir -p krcl_output

      - name: Download and archive each show individually
        run: |
          chmod +x krcl.sh

          # Loop through the past 12 months
          for i in {0..11}; do
            DATE=$(date -d "-$i month" +%Y-%m)
            echo "Processing shows for $DATE..."

            # Use krcl.sh scraping logic to get the list of shows
            AVAILABLE_SHOWS=$(./krcl.sh "$DATE" | grep -oP '(?<=  )[0-9]+\) [^\)]+$' | awk '{print $2}')
            
            # Iterate over each show and download, then archive it
            for SHOW in $AVAILABLE_SHOWS; do
              echo "Downloading and archiving show: $SHOW for $DATE..."

              # Simulate downloading the show (replace with actual logic if needed)
              mkdir -p "krcl_output/$SHOW"
              echo "Mock content for $SHOW on $DATE" > "krcl_output/$SHOW/${SHOW}_${DATE}.mp3"

              # Archive the downloaded show
              tar -I 'zstd -T0 -19' -cf "krcl_output/${SHOW}_${DATE}.tzst" "krcl_output/$SHOW"

              # Clean up the temporary files for the show
              rm -rf "krcl_output/$SHOW"
            done
          done

      - name: Upload individual archives
        uses: actions/upload-artifact@v4
        with:
          name: krcl_individual_show_archives
          path: krcl_output/*.tzst
